== 사전

=== 작성 API

operation::dictionary-save[snippets="http-request,request-body,request-fields,http-response,response-fields"]

=== 수정 API

operation::dictionary-update[snippets="path-parameters,http-request,request-body,request-fields,http-response,response-fields"]

=== 최근 작성/편집된 조회 API

operation::dictionary-getTop20Dictionaries[snippets="http-request,http-response,response-fields"]

=== 카테고리별 조회 API

operation::dictionary-getGroupDictionaries[snippets="path-parameters,http-request,http-response,response-fields"]

=== 기록 조회 API

operation::dictionary-get[snippets="path-parameters,http-request,http-response,response-fields"]

=== 기록 목록 조회 API

operation::dictionary-getHistories[snippets="path-parameters,http-request,http-response,response-fields"]

=== 제목 검색 API

operation::dictionary-searchByTitle[snippets="query-parameters,http-request,http-response,response-fields"]

=== 랜덤 조회 API

operation::dictionary-getRandomDictionary[snippets="http-request,http-response,response-fields"]

=== 인기도 순으로 조회 API

operation::dictionary-getPopular[snippets="http-request,http-response,response-fields"]