server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

cors:
  path-pattern: /**
  origins: http://localhost:5173
  methods: POST, GET, PUT, PATCH, DELETE, OPTIONS
  headers: "*"
  allow-credentials: true
  max-age: 3600
