services:
  app:
    container_name: taleswiki
    image: openmpy/taleswiki-server:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs
    depends_on:
      - redis
      - elasticsearch

  redis:
    container_name: redis
    image: redis:7.4.2
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    restart: unless-stopped
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data

volumes:
  redis:
  es:
