services:
  server:
    container_name: taleswiki-server
    image: openmpy/taleswiki-server:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:7.4.2
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

volumes:
  redis:
