services:
  app:
    image: openmpy/taleswiki-server:latest
    container_name: taleswiki
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./logs:/logs
    restart: unless-stopped
    networks:
      - default

  redis:
    container_name: redis
    image: redis:7.4.2
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
      - default

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - es:/usr/share/elasticsearch/data
    restart: unless-stopped
    networks:
      - default

volumes:
  redis:
  es:

networks:
  default:
