{
 "title": "Spring Boot JDBC & HikariCP",
 "description": "Spring Boot (Micrometer) with JDBC and HikariCP.",
 "tags": [
  "prometheus",
  "spring-boot",
  "micrometer",
  "jdbc",
  "hikaricp"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(jdbc_connections_max, namespace)"
    }
   },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(jdbc_connections_max{namespace=\"$namespace\"}, application)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jdbc_connections_max{namespace=\"$namespace\", application=\"$application\"}, instance)"
    }
   },
   {
    "name": "jdbc_connection_name",
    "label": "JDBC",
    "query": {
     "query": "label_values(jdbc_connections_max{namespace=\"$namespace\",application=\"$application\", instance=~\"$instance\"}, name)"
    }
   },
   {
    "name": "hikaricp_connection_name",
    "label": "HikariCP",
    "query": {
     "query": "label_values(hikaricp_connections_max{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\"}, pool)"
    }
   }
  ]
 },
 "panels": [
  { "title": "JDBC: $jdbc_connection_name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "jdbc_connection_name" },
  {
   "title": "Idle / Active",
   "type": "timeseries",
   "description": "History of idle/active.",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(jdbc_connections_active{namespace=\"$namespace\", application=\"$application\", name=\"$jdbc_connection_name\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(jdbc_connections_idle{namespace=\"$namespace\", application=\"$application\", name=\"$jdbc_connection_name\"})",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Active",
   "type": "stat",
   "description": "Current number of active connections that have been allocated from the data source.",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jdbc_connections_active{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", name=\"$jdbc_connection_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Idle",
   "type": "stat",
   "description": "Number of established but idle connections.",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jdbc_connections_idle{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", name=\"$jdbc_connection_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Min / Max",
   "type": "timeseries",
   "description": "History of min/max.",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(jdbc_connections_max{namespace=\"$namespace\", application=\"$application\", name=\"$jdbc_connection_name\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(jdbc_connections_min{namespace=\"$namespace\", application=\"$application\", name=\"$jdbc_connection_name\"})",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Max",
   "type": "stat",
   "description": "Maximum number of active connections that can be allocated at the same time.",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jdbc_connections_max{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", name=\"$jdbc_connection_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Min",
   "type": "stat",
   "description": "Minimum number of idle connections in the pool.",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jdbc_connections_min{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", name=\"$jdbc_connection_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HikariCP: $hikaricp_connection_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "repeat": "hikaricp_connection_name"
  },
  {
   "title": "Idle / Active / Pending",
   "type": "timeseries",
   "description": "History of idle/active.",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_active{namespace=\"$namespace\", application=\"$application\", pool=\"$hikaricp_connection_name\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(hikaricp_connections_pending{namespace=\"$namespace\", application=\"$application\", pool=\"$hikaricp_connection_name\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(hikaricp_connections_idle{namespace=\"$namespace\", application=\"$application\", pool=\"$hikaricp_connection_name\"})",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Active",
   "type": "stat",
   "description": "Active connections.",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_active{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", pool=\"$hikaricp_connection_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Idle",
   "type": "stat",
   "description": "Idle connections.",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_idle{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", pool=\"$hikaricp_connection_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Min / Max",
   "type": "timeseries",
   "description": "History of min/max.",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_max{namespace=\"$namespace\", application=\"$application\", pool=\"$hikaricp_connection_name\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(hikaricp_connections_min{namespace=\"$namespace\", application=\"$application\", pool=\"$hikaricp_connection_name\"})",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Max",
   "type": "stat",
   "description": "Max connections.",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_max{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", pool=\"$hikaricp_connection_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Min",
   "type": "stat",
   "description": "Min connections.",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_min{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", pool=\"$hikaricp_connection_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Usage / Acquire / Creation",
   "type": "timeseries",
   "description": "History of timeouts.",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(hikaricp_connections_usage_seconds_sum{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", pool=\"$hikaricp_connection_name\"}[$__rate_interval]) / irate(hikaricp_connections_usage_seconds_count{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", pool=\"$hikaricp_connection_name\"}[$__rate_interval]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(irate(hikaricp_connections_acquire_seconds_sum{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", pool=\"$hikaricp_connection_name\"}[$__rate_interval]) / irate(hikaricp_connections_acquire_seconds_count{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", pool=\"$hikaricp_connection_name\"}[$__rate_interval]))",
     "legendFormat": "Acquire"
    },
    {
     "expr": "sum(irate(hikaricp_connections_creation_seconds_sum{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", pool=\"$hikaricp_connection_name\"}[$__rate_interval]) / irate(hikaricp_connections_creation_seconds_count{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", pool=\"$hikaricp_connection_name\"}[$__rate_interval]))",
     "legendFormat": "Creation"
    }
   ]
  },
  {
   "title": "Max usage",
   "type": "stat",
   "description": "Max time on usage.",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_usage_seconds_max{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", pool=\"$hikaricp_connection_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max acquire",
   "type": "stat",
   "description": "Max time on acquiring.",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_acquire_seconds_max{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", pool=\"$hikaricp_connection_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max creation",
   "type": "stat",
   "description": "Max time on creation.",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_creation_seconds_max{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", pool=\"$hikaricp_connection_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}