name: Deploy to EC2

on:
  push:
    branches:
      - main

deploy:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./server
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/taleswiki-server:latest
        build-args: |
          JAR_FILE=build/app.jar

    - name: Copy compose.yml to server
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_SSH_USER }}
        password: ${{ secrets.EC2_SSH_PASSWORD }}
        source: "server/compose.yml"
        target: "/home/taleswiki/server"
        strip_components: 0

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_SSH_USER }}
        password: ${{ secrets.EC2_SSH_PASSWORD }}
        script: |
          cd /home/taleswiki/server
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/taleswiki-server:latest
          docker compose down || true
          docker compose up -d